Repository deividafonso281/saude_mental, pull requests merged in 2023-06, with the labels that each got.

#24 Feature/cadastro especialistas bruno
  frontend/lib/cadastro_especialista.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/test/cadastro_especialista_test.dart
  frontend/workflows/cadastro_especialist.yaml
Labels: AvaliacaoA2

#26 Teste/testando firebase sync
  frontend/.gitignore
  frontend/android/app/build.gradle
  frontend/android/build.gradle
  frontend/lib/main.dart
  frontend/lib/screens/auth/Login_screen.dart
  frontend/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/windows/flutter/generated_plugin_registrant.cc
  frontend/windows/flutter/generated_plugins.cmake
Labels: AvaliacaoA2

#31 Delete cadastro_especialista.dart
  frontend/lib/cadastro_especialista.dart
Labels: AvaliacaoA2

#34 Feature/cadastro pacientes
  .github/workflows/cadastro_paciente_job.yaml
  .idea/.gitignore
  .idea/modules.xml
  .idea/saude_mental.iml
  .idea/vcs.xml
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/ios/Flutter/Debug.xcconfig
  frontend/ios/Flutter/Release.xcconfig
  frontend/ios/Podfile
  frontend/ios/Podfile.lock
  frontend/ios/Runner.xcodeproj/project.pbxproj
  frontend/ios/Runner.xcworkspace/contents.xcworkspacedata
  frontend/ios/Runner/Info.plist
  frontend/lib/cadastro_paciente.dart
  frontend/lib/main.dart
  frontend/linux/flutter/generated_plugin_registrant.cc
  frontend/linux/flutter/generated_plugins.cmake
  frontend/macos/Flutter/Flutter-Debug.xcconfig
  frontend/macos/Flutter/Flutter-Release.xcconfig
  frontend/macos/Podfile
  frontend/macos/Podfile.lock
  frontend/macos/Runner.xcodeproj/project.pbxproj
  frontend/macos/Runner.xcworkspace/contents.xcworkspacedata
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/test/cadastro_paciente_test.dart
  frontend/windows/flutter/generated_plugin_registrant.cc
  frontend/windows/flutter/generated_plugins.cmake
Labels: AvaliacaoA2

#36 Feature/teste login screen
  .github/workflows/cadastro_paciente_job.yaml
  .idea/.gitignore
  .idea/modules.xml
  .idea/saude_mental.iml
  .idea/vcs.xml
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/ios/Flutter/Debug.xcconfig
  frontend/ios/Flutter/Release.xcconfig
  frontend/ios/Podfile
  frontend/ios/Podfile.lock
  frontend/ios/Runner.xcodeproj/project.pbxproj
  frontend/ios/Runner.xcworkspace/contents.xcworkspacedata
  frontend/ios/Runner/Info.plist
  frontend/lib/app_builder.dart
  frontend/lib/main.dart
  frontend/lib/providers/auth_provider.dart
  frontend/lib/screens/auth/cadastro_paciente.dart
  frontend/lib/screens/auth/common.dart
  frontend/lib/screens/auth/login_screen.dart
  frontend/lib/screens/auth/register/cadastro_especialista_screen.dart
  frontend/lib/screens/auth/register/intermediete_register_screen.dart
  frontend/lib/screens/search/busca_psicologo_screen.dart
  frontend/lib/screens/search/card_psicologo.dart
  frontend/lib/screens/search/lista_psicologos.dart
  frontend/lib/utils/router.dart
  frontend/macos/Flutter/Flutter-Debug.xcconfig
  frontend/macos/Flutter/Flutter-Release.xcconfig
  frontend/macos/Podfile
  frontend/macos/Podfile.lock
  frontend/macos/Runner.xcodeproj/project.pbxproj
  frontend/macos/Runner.xcworkspace/contents.xcworkspacedata
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/test/cadastro_especialista_test.dart
  frontend/test/cadastro_paciente_test.dart
  frontend/test/lista_terapeutas_test.dart
Labels: AvaliacaoA2

#37 Develop
  .github/workflows/dart.yml
  frontend/lib/main.dart
  frontend/lib/providers/auth_provider.dart
  frontend/lib/screens/auth/cadastro_paciente.dart
  frontend/lib/screens/auth/common.dart
  frontend/lib/screens/auth/login_screen.dart
  frontend/lib/screens/auth/register/cadastro_especialista_screen.dart
  frontend/lib/screens/auth/register/intermediete_register_screen.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/test/cadastro_especialista_test.dart
  frontend/test/cadastro_paciente_test.dart
Labels: AvaliacaoA2

#39 Feature/backend
  frontend/lib/app_builder.dart
  frontend/lib/auth_builder.dart
  frontend/lib/firebase_options.dart
  frontend/lib/main.dart
  frontend/lib/models/auth_model.dart
  frontend/lib/models/base_model.dart
  frontend/lib/models/convertos/map_converter_factory.dart
  frontend/lib/models/convertos/map_converter_interface.dart
  frontend/lib/models/especialist_model.dart
  frontend/lib/models/user_model.dart
  frontend/lib/providers/auth/auth_provider.dart
  frontend/lib/providers/database/database_service.dart
  frontend/lib/providers/database/firebase/firestore_general _dao.dart
  frontend/lib/providers/database/firebase/firestore_service.dart
  frontend/lib/providers/database/firebase/paths/especialist_firestore_path.dart
  frontend/lib/providers/database/firebase/paths/firestore_paths_factory.dart
  frontend/lib/providers/database/firebase/paths/firestore_paths_interface.dart
  frontend/lib/providers/database/firebase/paths/user_firestore_path.dart
  frontend/lib/screens/auth/cadastro_paciente.dart
  frontend/lib/screens/auth/common.dart
  frontend/lib/screens/auth/login_screen.dart
  frontend/lib/screens/auth/register/intermediete_register_screen.dart
  frontend/lib/screens/auth/register/register_screen.dart
  frontend/lib/screens/search/busca_psicologo_screen.dart
  frontend/lib/utils/router.dart
  frontend/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/test/auth_common_test.dart
  frontend/test/cadastro_paciente_test.dart
Labels: AvaliacaoA4.1

#40 Develop
  frontend/lib/app_builder.dart
  frontend/lib/auth_builder.dart
  frontend/lib/firebase_options.dart
  frontend/lib/main.dart
  frontend/lib/models/auth_model.dart
  frontend/lib/models/base_model.dart
  frontend/lib/models/convertos/map_converter_factory.dart
  frontend/lib/models/convertos/map_converter_interface.dart
  frontend/lib/models/especialist_model.dart
  frontend/lib/models/user_model.dart
  frontend/lib/providers/auth/auth_provider.dart
  frontend/lib/providers/database/database_service.dart
  frontend/lib/providers/database/firebase/firestore_general _dao.dart
  frontend/lib/providers/database/firebase/firestore_service.dart
  frontend/lib/providers/database/firebase/paths/especialist_firestore_path.dart
  frontend/lib/providers/database/firebase/paths/firestore_paths_factory.dart
  frontend/lib/providers/database/firebase/paths/firestore_paths_interface.dart
  frontend/lib/providers/database/firebase/paths/user_firestore_path.dart
  frontend/lib/screens/auth/cadastro_paciente.dart
  frontend/lib/screens/auth/common.dart
  frontend/lib/screens/auth/login_screen.dart
  frontend/lib/screens/auth/register/intermediete_register_screen.dart
  frontend/lib/screens/auth/register/register_screen.dart
  frontend/lib/screens/search/busca_psicologo_screen.dart
  frontend/lib/utils/router.dart
  frontend/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/test/auth_common_test.dart
  frontend/test/cadastro_paciente_test.dart
Labels: AvaliacaoA4.1

#58 Implementando casos de teste por particionamento em classes de equiva…
  frontend/lib/screens/auth/common.dart
  frontend/lib/screens/auth/register/register_screen.dart
  frontend/test/validation_tests.dart
Labels: Avaliacao A5
